FROM debian:trixie-slim

# install github apt repo
#
RUN apt-get update && apt-get install -y wget

RUN mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
        | tee /etc/apt/sources.list.d/github-cli.list > /dev/null

# install useful packages
#
RUN apt-get update && apt-get install -y \
    curl \
    ripgrep \
    neovim \
    fd-find \
    fzf

# install github cli
#
RUN apt update && apt install -y gh

# create users
#
RUN groupadd nerds
RUN useradd -g nerds -ms /bin/bash claude
RUN useradd -g nerds -ms /bin/bash nerd \
    && usermod -aG sudo nerd # grant nerd sudo access

# install claude
#
USER claude
WORKDIR /home/claude

RUN curl -fsSL https://claude.ai/install.sh | bash
RUN chmod g+rwx /home/claude

# become runtime user
#
USER nerd
WORKDIR /home/nerd

CMD ["/bin/bash"]