FROM debian:trixie-slim

# install deps
RUN apt-get update && apt-get install -y \
    curl \
    wget

# install github apt repo
RUN mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out |  tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" |  tee /etc/apt/sources.list.d/github-cli.list > /dev/null


# install github cli
RUN apt update && apt install -y gh

# install claude
RUN curl -fsSL https://claude.ai/install.sh | bash

# install packages
RUN apt-get update && apt-get install -y \
    ripgrep \
    vim

COPY .bashrc /root

CMD ["/bin/bash"]
